- name: install packages 
  hosts: all
  become: yes
  tasks:
    - name: install nginx
      ansible.buitin.package:
        name: nginx
        state: latest
    - name: install httd
      ansible.builtin.package:
        name: tomcat
        state: latest

     
