- name: install packages 
  hosts: all
  become: yes
  tasks:
    - name: install nginx
      ansible.builtin.package:
        name: nginx
        state: latest
        
    - name: install httd
      ansible.builtin.package:
        name: tomcat
        state: latest

  # - name: Install packages
  #   hosts: all
  #   become: yes
  #   tasks:
  #     - name: Install Nginx
  #       ansible.builtin.package:
  #         name: nginx
  #         state: latest

  #     - name: Install Tomcat
  #       ansible.builtin.package:
  #         name: tomcat
  #         state: latest


     
